// export const url="https://esimwawtelecom.com/wawapi/api/"
export const url="http://localhost:8000/api/"
// export const url="https://esimwawtelecom.com/wawapi/api/"
// export const url="https://esimwawtelecom.com/wawbackend/public/api/"
// export const url="https://www.esimwawtelecom.com/wawesim/public/api/"